### ISSUE TITLE
Design of tools within ncimonitor

### ISSUE THREAD

**Issue by ccarouge** [coecms/ncimonitor#14]
@ScottWales @aidanheerdegen When building the tool for reporting I found some useful stuff in both ncimonitor and nciusage. But since nciusage main class is independent from ncimonitor main class, mixing both was annoying. For example, ncimonitor uses dataset to connect to the db but nciusage uses sqlite3. 
If we want to build more tools on the db, would it make sense to rethink the design? For example, a simple superclass with __init__ only to connect to the db + a few informative attributes and sub-classes of this used in tools? So we ensure some coherence in objects? Or am I just not experienced enough in Python?

**Comment by aidanheerdegen** [comment]
I agree it isn't well suited for extension to more general tasks.

I originally used dataset because I didn't want to stuff around with SQL queries. As it turns out, I ended up stuffing around with SQL queries anyway.

`nci_usage.py` could be re-written using dataset, or vice-versa.

**Comment by ScottWales** [comment]
Makes sense to be consistent, I have no strong feelings one way or the other which to use
