### ISSUE TITLE
make /short plots more useful

### ISSUE THREAD

**Issue by ccarouge** [coecms/ncimonitor#2]
Maybe reduce the number of users in the /short plots to show only those using more than X% of the storage or the X biggest users or the users that account for X% of the total storage and just one aggregated user for the rest?

**Comment by aidanheerdegen** [comment]
There is now a `--cutoff` option in https://github.com/coecms/ncimonitor/commit/f8d66dad0cd2cd538d63850daf5caf72783905f1
